### ISSUE TITLE
`getColors` could automatically handle some stretched elements.

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#1260]
We've seen a few time patterns like:
```css
.stretched {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  background-color: red;
}
```
In this case, `getColors` bail out due to interposed descendant. However, the stretching to `0` on all four sides means that the element will exactly cover it's offset parent. So we could directly use this color instead.
This requires care in handling the painting order to detect what is below and what is on top (so, need to look into the DOM order, which does make the recurrence in `getLayer` more tricky to correctly handle). It seems, however, that when this is actually used to set background, this is done on the first children…
