### ISSUE TITLE
Security restrictions on which properties may be set by declarations using the `:visited` selector are not accounted for

### ISSUE THREAD

**Issue by kasperisager** [Siteimprove/alfa#708]
https://developer.mozilla.org/en-US/docs/Web/CSS/:visited#privacy_restrictions

As an example, this currently means that `Style#computed()` applies the `text-decoration` property set by the following declaration, which affects SIA-R62:

```css
a:visited {
  text-decoration: none;
}
```
