### ISSUE TITLE
SIA-R62 should accept differences in `box-shadow`

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#888]
Yet another way of removing the default underline and replace it with a custom one 🙄 

```css
a {
  box-shadow: inset 0 -1px 0 rgb(0 38 99 / 30%);
  text-decoration: none;
}
```
