### ISSUE TITLE
SIA-R62 should accept more differences in `font`

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#952]
Currently only accepting differences in `font-weight`.
Seen a case like
```css
p { font-family: VAGRoundedStd-Light}
a { font-family: VAGRoundedStd-Bold}
```
