### ISSUE TITLE
Investigate better handling of pseudo-elements

### ISSUE THREAD

**Issue by Jym77** [Siteimprove/alfa#954]
Pseudo-elements can be used to inject a background colour, dropping them causes false positives in R69 (among other).

```css
.advance-header-inner .content-left::before {
  background: #FC5D0D;
  border-radius: 0 30px 30px 0;
}
```

---
Pseudo-element can also be used to show focus indicator:
```css
.foo:focus::after {
  position: absolute;
  top: -4px;
  right: -8px;
  bottom: -4px;
  left: -8px;
  content: "";
  display: block;
  border: 2px solid #b51133;
  border-radius: 0.25rem;
}
```

---
Pseudo-elements can be used to inject (part of) accessible name: [Accessible name testable statement 552](https://www.w3.org/wiki/AccName_1.1_Testable_Statements#Name_test_case_552) (and several others).

- [ ] Follow up on DEV-12423
- [ ] Follow up on DEV-12462
- [ ] Follow up on CST-2609
